name: NavyCraft
main: com.maximuspayne.navycraft.NavyCraft
<<<<<<< HEAD
version: 2.8.4
=======
version: 2.8.3
>>>>>>> aecebfd6d00c6bfb016d48a9cbd3c9f915f30c49
authors: [Maximuspayne, Solmex, Premejo, SycoPrime, Yogoda]
depend: [WorldGuard,WorldEdit,Essentials,PermissionsEx]

commands:
   navycraft:
      description: Ship and other vehicle based commands
      usage:
           /<command>
   ship:
      description: Ship
   aircraft:
      description: Aircraft
   submarine:
      description: Submarine